import { Link } from "react-router-dom";
import { Wordmark } from "../components/Shell";

export default function Terms() {
  return (
    <main className="mx-auto max-w-[760px] px-5 py-6 md:px-8">
      <Link to="/" aria-label="Lyra Studio home">
        <Wordmark />
      </Link>
      <h1 className="display mt-14 text-5xl">Terms</h1>
      <p className="mt-3 text-sm text-slate">Last updated 3 October 2026</p>
      <div className="mt-8 space-y-6 text-[0.98rem] leading-relaxed">
        <section>
          <h2 className="font-medium">What Lyra Studio does</h2>
          <p className="mt-1 text-slate">
            You upload a song. Lyra Studio measures it, sends those measurements (not the audio) to an AI
            text model to write image briefs, and sends the briefs to an AI image model to paint images.
          </p>
        </section>
        <section>
          <h2 className="font-medium">Your songs</h2>
          <p className="mt-1 text-slate">
            Only upload music you own or have permission to use. Uploaded audio is stored privately on the
            Lyra Studio server so you can play it back and make more images. It is never shared with other
            users and is not sent to the AI services. You can delete a song and all of its images at any
            time from the song's page.
          </p>
        </section>
        <section>
          <h2 className="font-medium">Images</h2>
          <p className="mt-1 text-slate">
            Images are generated by Google's Gemini image model from briefs written by Anthropic's Claude.
            They are stored in your account and are yours to download and use. Lyra Studio makes no claim
            on them, and does not guarantee they are free of resemblance to existing works.
          </p>
        </section>
        <section>
          <h2 className="font-medium">Limits</h2>
          <p className="mt-1 text-slate">
            Accounts are by invitation and have a daily allowance of uploads and images, shown in Settings.
            Lyra Studio is a research prototype and may be changed or taken offline without notice.
          </p>
        </section>
        <section>
          <h2 className="font-medium">Contact</h2>
          <p className="mt-1 text-slate">Questions go to Runbao Du at durunbao.com.</p>
        </section>
      </div>
    </main>
  );
}
